package net.sf.mardao.test.jdbc.dao;

/**
 * Implementation of Business Methods related to entity Chapter.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2011-09-04T10:34:57.651+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class ChapterDaoBean 
	extends GeneratedChapterDaoImpl
		implements ChapterDao 
{

	// TODO: implement your Business Methods here

}
