package net.sf.mardao.test.jdbc.dao;

/**
 * Business Methods interface for entity Chapter.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2011-09-06T18:51:36.493+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface ChapterDao extends GeneratedChapterDao<Long, Long> {

	// TODO: declare your Business Methods here
	
}
