package net.sf.mardao.test.jdbc.dao;

/**
 * Implementation of Business Methods related to entity Footnote.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2011-09-06T18:48:34.165+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class FootnoteDaoBean 
	extends GeneratedFootnoteDaoImpl
		implements FootnoteDao 
{

	// TODO: implement your Business Methods here

}
