package net.sf.mardao.test.jdbc.dao;


/**
 * Business Methods interface for entity Footnote.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-01-04T13:16:36.489+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface FootnoteDao 
    extends GeneratedFootnoteDao<java.lang.Long, java.lang.Long> {

	// TODO: declare your Business Methods here
	
}
