package net.sf.mardao.core.dao;

/**
 * Business Methods interface for entity DUnique.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-04-11T17:34:57.203+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DUniqueDao extends GeneratedDUniqueDao {

	// TODO: declare your Business Methods here
	
}
