package net.sf.mardao.core.dao;

/**
 * Implementation of Business Methods related to entity DUnique.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-04-11T17:34:57.203+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DUniqueDaoBean 
	extends GeneratedDUniqueDaoImpl
		implements DUniqueDao 
{

	// TODO: implement your Business Methods here

}
