package net.sf.mardao.core.dao;

/**
 * Implementation of Business Methods related to entity ExtendsBean.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-04-09T16:13:40.169+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class ExtendsBeanDaoBean 
	extends GeneratedExtendsBeanDaoImpl
		implements ExtendsBeanDao 
{

	// TODO: implement your Business Methods here

}
