package net.sf.mardao.core.dao;

/**
 * Business Methods interface for entity IdBean.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-04-09T16:13:40.169+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface IdBeanDao extends GeneratedIdBeanDao {

	// TODO: declare your Business Methods here
	
}
