package net.sf.mardao.test.aed.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity Appendix.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2011-09-23T10:07:47.780+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface AppendixDao extends GeneratedAppendixDao<Key, Key> {

	// TODO: declare your Business Methods here
	
}
