package net.sf.mardao.test.aed.dao;

/**
 * Implementation of Business Methods related to entity Appendix.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2011-09-23T10:07:47.780+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class AppendixDaoBean 
	extends GeneratedAppendixDaoImpl
		implements AppendixDao 
{

	// TODO: implement your Business Methods here

}
