package net.sf.mardao.test.aed.dao;

/**
 * Implementation of Business Methods related to entity DCategory.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-11T12:58:15.222+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DCategoryDaoBean 
	extends GeneratedDCategoryDaoImpl
		implements DCategoryDao 
{

    // to enable caching
    public DCategoryDaoBean() {
        this.memCacheAll = true;
        this.memCacheEntity = true;
    }

}
