package net.sf.mardao.test.aed.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity DCategory.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-08-11T12:58:15.222+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DCategoryDao extends GeneratedDCategoryDao<Key, Key> {

	// TODO: declare your Business Methods here
	
}
