package net.sf.mardao.test.aed.dao;

import com.google.appengine.api.datastore.Key;

/**
 * Business Methods interface for entity Page.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 */
public interface PageDao extends GeneratedPageDao<Key, Key> {

	// TODO: declare your Business Methods here
	
}
