package net.sf.mardao.test.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;
import javax.cache.annotation.CacheDefaults;

/**
 * Implementation of Business Methods related to entity DCachedEntity.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2015-01-20T15:47:37.626+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
@CacheDefaults(cacheName = "DCachedEntity")
public class DCachedEntityDaoBean 
	extends GeneratedDCachedEntityDaoImpl
{

  @Inject
  public DCachedEntityDaoBean(Supplier supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
