package net.sf.mardao.test.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DChild.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-10-01T19:57:05.382+0200.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DChildDaoBean 
	extends GeneratedDChildDaoImpl
{

  @Inject
  public DChildDaoBean(Supplier supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
