package net.sf.mardao.test.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DEntity.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2014-09-14T18:41:01.737+0200.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DEntityDaoBean 
	extends GeneratedDEntityDaoImpl
{

  @Inject
  public DEntityDaoBean(Supplier supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
