package net.sf.mardao.test.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;
import net.sf.mardao.core.CacheConfig;

/**
 * Implementation of Business Methods related to entity DPageCachedEntity.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2015-01-20T15:15:31.823+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
@CacheConfig(name = "DPageCachedEntity")
public class DPageCachedEntityDaoBean 
	extends GeneratedDPageCachedEntityDaoImpl
{

  @Inject
  public DPageCachedEntityDaoBean(Supplier supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
