package net.sf.mardao.junit.dao;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DUser.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2015-02-28T10:34:05.595+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DUserDaoBean 
	extends GeneratedDUserDaoImpl
{

  public DUserDaoBean(Supplier<Object, Object, Object, Object> supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
