package net.sf.mardao.api.dao;

/**
 * Business Methods interface for entity DEmployee.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-12T18:26:46.676+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DEmployeeDao extends GeneratedDEmployeeDao {

	// TODO: declare your Business Methods here
	
}
