package net.sf.mardao.api.dao;

/**
 * Implementation of Business Methods related to entity DGroup.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-12T18:26:46.676+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DGroupDaoBean 
	extends GeneratedDGroupDaoImpl
		implements DGroupDao 
{

	// TODO: implement your Business Methods here

}
