package net.sf.mardao.api.dao;

/**
 * Business Methods interface for entity DInventory.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-15T20:34:24.069+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DInventoryDao extends GeneratedDInventoryDao {

	// TODO: declare your Business Methods here
	
}
