package net.sf.mardao.test.dao;

/**
 * Business Methods interface for entity DCrossPrinter.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-02T10:38:15.929+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DCrossPrinterDao extends GeneratedDCrossPrinterDao {

	// TODO: declare your Business Methods here
	
}
