package net.sf.mardao.test.dao;

/**
 * Implementation of Business Methods related to entity DCrossPrinter.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-02T10:38:15.929+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DCrossPrinterDaoBean 
	extends GeneratedDCrossPrinterDaoImpl
		implements DCrossPrinterDao 
{

	// TODO: implement your Business Methods here

}
