package net.sf.mardao.test.dao;

/**
 * Implementation of Business Methods related to entity DInventory.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-09-17T08:51:16.825+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DInventoryDaoBean 
	extends GeneratedDInventoryDaoImpl
		implements DInventoryDao 
{

	// TODO: implement your Business Methods here

}
