package net.sf.mardao.manytomany.dao;

/**
 * Business Methods interface for entity AndroidManyToMany.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-05-05T17:25:30.176+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface AndroidManyToManyDao extends GeneratedAndroidManyToManyDao<Long, Long>,
    GeneratedAndroidManyToManyDaoAndroid {

	// TODO: declare your Business Methods here
	
}
