package net.sf.mardao.test.dao;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DBasic.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2015-02-24T19:51:12.400+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DBasicDaoBean 
	extends GeneratedDBasicDaoImpl
{

  public DBasicDaoBean(Supplier<Object, Object, Object, Object> supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
